# 1번문제

## 파일 불러오기

In [9]:
import pandas as pd
df = pd.read_csv('cafe_daily_sales.csv')
df.head()

         date day_of_week  temperature  foot_traffic  promotion  sales
0  2026-03-02         Mon          5.8         471.0          1  286.9
1  2026-03-03         Tue          2.6         559.0          0  302.7
2  2026-03-04         Wed          7.3         425.0          0  276.9
3  2026-03-05         Thu          8.0         484.0          0  246.2
4  2026-03-06         Fri          1.0         424.0          1  303.3

In [10]:
cafe_daily_sales_df = pd.DataFrame({
    '열이름' : ['date', 'day_of_week', 'temperature', 'foot_traffic', 'promotion', 'sales'],
    '의미' : ['날짜', '요일 (Mon~Sun)', '평균기온(°C)', '매장 앞 유동인구(명)', '프로모션 진행 여부 (1=진행, 0=미진행)', '일 매출 (만원)']
})

cafe_daily_sales_df

            열이름                        의미
0          date                        날짜
1   day_of_week              요일 (Mon~Sun)
2   temperature                  평균기온(°C)
3  foot_traffic              매장 앞 유동인구(명)
4     promotion  프로모션 진행 여부 (1=진행, 0=미진행)
5         sales                 일 매출 (만원)

## 중복확인하기

In [11]:
cafe_daily_sales_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool